# Generated by Django 5.2.3 on 2025-06-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_raciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raciones',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
