# Generated by Django 5.2.3 on 2025-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_sopas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipicos',
            name='imagen',
            field=models.ImageField(default=None, upload_to='platos_tipicos/'),
            preserve_default=False,
        ),
    ]
