# Generated by Django 5.2.3 on 2025-07-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_tipicos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrantes',
            name='imagen',
            field=models.ImageField(default=None, upload_to='entrantes/'),
            preserve_default=False,
        ),
    ]
