# Generated by Django 5.2.3 on 2025-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_entrantes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopas',
            name='imagen',
            field=models.ImageField(default=None, upload_to='sopas/'),
            preserve_default=False,
        ),
    ]
