# Generated by Django 5.2.3 on 2025-07-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_ensaldas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ensaldas',
            new_name='Ensaladas',
        ),
    ]
